name: UQ Alphas Game Notification

on:
  schedule:
    # Run every day at 4:00 AM UTC (2:00 PM Brisbane time)
    - cron: '0 4 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  notify-game:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Set up environment variables
      run: |
        echo "ULTRA_MSG_TOKEN=${{ secrets.ULTRA_MSG_TOKEN }}" >> $GITHUB_ENV
        echo "ULTRA_MSG_INSTANCE_ID=${{ secrets.ULTRA_MSG_INSTANCE_ID }}" >> $GITHUB_ENV
        echo "DEFAULT_PHONE_NUMBER=${{ secrets.DEFAULT_PHONE_NUMBER }}" >> $GITHUB_ENV
        
    - name: Run game notification script
      run: python main.py
      
    - name: Upload logs (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        path: |
          *.log
          selenium-debug.log 